-- 24 supplements and 12 peptides, four and two per goal, five articles each.
--
-- PRODUCTS. Every supplement is a real, specific, branded product resolved
-- against the NIH Dietary Supplement Label Database. The brand, the product
-- name and the form all came back from DSLD for that exact label, and
-- label_url points at the filing so any of it can be checked. No brand here
-- was invented -- a made-up product in a catalogue people buy from is not a
-- placeholder, it is a fabrication, and it would send someone looking for
-- something that does not exist.
--
-- The twelve peptides keep their compound names. Research peptides are not
-- dietary supplements, no authoritative product register covers them, and
-- inventing brands for them would be exactly the thing avoided above.
--
-- ARTICLES. 180 citations, each resolved against the PubMed E-utilities API:
-- esearch returned the PMID, esummary returned the title, journal and year for
-- that record. Every link opens the paper it names.
--
-- Descriptions stay categorical -- mechanism at the pattern level, storage,
-- route type. No dosing, no frequency, no protocol. See legal.md. Where a
-- product's own label carries a strength it is part of the manufacturer's
-- product name, not a recommendation by this app.

alter table public.glossary
  add column if not exists kind text not null default 'peptide',
  add column if not exists brand text,
  add column if not exists product_form text,
  add column if not exists label_url text;
alter table public.glossary drop constraint if exists glossary_kind_check;
alter table public.glossary add constraint glossary_kind_check
  check (kind in ('peptide', 'supplement'));

insert into public.glossary (slug, name, category, mechanism_summary, storage_notes, route, research_summary, goal_tags, kind, brand, product_form, label_url)
values
  ('collagen-peptides', 'Vital Proteins Collagen Peptides', 'cosmetic',
   'Hydrolysed collagen broken into short peptides, studied for whether oral intake influences dermal collagen density and joint tissue.',
   'Store cool and dry.',
   'oral',
   'Commonly studied for skin elasticity, hydration and joint comfort outcomes. This entry is the Vital Proteins Collagen Peptides label as filed with the NIH Dietary Supplement Label Database.',
   array['Skin', 'Anti-Aging'], 'supplement', 'Vital Proteins', 'Capsule', 'https://dsld.od.nih.gov/label/246526'),

  ('biotin', 'Finest Nutrition Biotin 5,000 mcg', 'cosmetic',
   'Vitamin B7, a cofactor for carboxylase enzymes, studied mainly in the context of keratin infrastructure.',
   'Store cool and dry.',
   'oral',
   'Commonly studied for hair and nail outcomes, and for its well-documented interference with laboratory assays. This entry is the Finest Nutrition Biotin 5,000 mcg label as filed with the NIH Dietary Supplement Label Database.',
   array['Skin'], 'supplement', 'Finest Nutrition', 'Capsule', 'https://dsld.od.nih.gov/label/60867'),

  ('vitamin-c', 'Gematria Vitamin C Complex', 'cosmetic',
   'Ascorbic acid, an essential cofactor for the enzymes that hydroxylate collagen, and a water-soluble antioxidant.',
   'Store cool and dry. Protect from light.',
   'oral',
   'Commonly studied for collagen synthesis, iron absorption and immune function. This entry is the Gematria Vitamin C Complex label as filed with the NIH Dietary Supplement Label Database.',
   array['Skin', 'Immune', 'Anti-Aging'], 'supplement', 'Gematria', 'Capsule', 'https://dsld.od.nih.gov/label/3254'),

  ('hyaluronic-acid', 'New Sun Hyaluronic Acid +', 'cosmetic',
   'A glycosaminoglycan native to skin and connective tissue, studied both topically and as an oral ingredient.',
   'Store cool and dry.',
   'oral',
   'Commonly studied for skin hydration and for joint space outcomes. This entry is the New Sun Hyaluronic Acid + label as filed with the NIH Dietary Supplement Label Database.',
   array['Skin', 'Anti-Aging'], 'supplement', 'New Sun', 'Capsule', 'https://dsld.od.nih.gov/label/217946'),

  ('magnesium-glycinate', 'Vinco''s Magnesium Glycinate', 'other',
   'Magnesium chelated to glycine, studied for NMDA and GABA receptor modulation and for its absorption profile relative to oxide salts.',
   'Store cool and dry.',
   'oral',
   'Commonly studied for sleep quality, muscle cramping and magnesium status. This entry is the Vinco''s Magnesium Glycinate label as filed with the NIH Dietary Supplement Label Database.',
   array['Sleep', 'Recovery'], 'supplement', 'Vinco''s', 'Powder', 'https://dsld.od.nih.gov/label/33919'),

  ('melatonin', 'Village Vitality Sleep with Valerian & Melatonin', 'other',
   'A hormone produced by the pineal gland in darkness, studied as a chronobiotic signal rather than a sedative.',
   'Store cool and dry. Protect from light.',
   'oral',
   'Commonly studied for sleep onset latency, jet lag and circadian phase shifting. This entry is the Village Vitality Sleep with Valerian & Melatonin label as filed with the NIH Dietary Supplement Label Database.',
   array['Sleep'], 'supplement', 'Village Vitality', 'Capsule', 'https://dsld.od.nih.gov/label/216782'),

  ('l-theanine', 'Woodstock Vitamins L-Theanine 200 mg', 'other',
   'An amino acid found in tea leaves, studied for alpha wave activity and for modulating the subjective effects of caffeine.',
   'Store cool and dry.',
   'oral',
   'Commonly studied for relaxation without sedation, and alongside caffeine for attention. This entry is the Woodstock Vitamins L-Theanine 200 mg label as filed with the NIH Dietary Supplement Label Database.',
   array['Sleep', 'Focus', 'Mood'], 'supplement', 'Woodstock Vitamins', 'Capsule', 'https://dsld.od.nih.gov/label/263070'),

  ('glycine', 'Protocol For Life Balance Glycine', 'other',
   'The smallest amino acid, an inhibitory neurotransmitter, studied for its effect on core body temperature before sleep.',
   'Store cool and dry.',
   'oral',
   'Commonly studied for subjective sleep quality and next-day fatigue. This entry is the Protocol For Life Balance Glycine label as filed with the NIH Dietary Supplement Label Database.',
   array['Sleep', 'Recovery'], 'supplement', 'Protocol For Life Balance', 'Powder', 'https://dsld.od.nih.gov/label/14922'),

  ('creatine-monohydrate', 'Pure Advantage Creatine Monohydrate', 'growth',
   'A compound stored in muscle as phosphocreatine, studied for rapid regeneration of ATP during short high-intensity effort.',
   'Store cool and dry.',
   'oral',
   'Commonly studied for strength, lean mass and, more recently, cognition. This entry is the Pure Advantage Creatine Monohydrate label as filed with the NIH Dietary Supplement Label Database.',
   array['Energy', 'Muscle', 'Recovery'], 'supplement', 'Pure Advantage', 'Powder', 'https://dsld.od.nih.gov/label/231495'),

  ('vitamin-b12', 'BulkSupplements.com Vitamin B12 1% (Methylcobalamin)', 'other',
   'Cobalamin, a cofactor for methionine synthase and methylmalonyl-CoA mutase, essential to red cell formation and myelin.',
   'Store cool and dry. Protect from light.',
   'oral',
   'Commonly studied for deficiency correction, particularly in vegan and older populations. This entry is the BulkSupplements.com Vitamin B12 1% (Methylcobalamin) label as filed with the NIH Dietary Supplement Label Database.',
   array['Energy', 'Focus'], 'supplement', 'BulkSupplements.com', 'Powder', 'https://dsld.od.nih.gov/label/311774'),

  ('iron-bisglycinate', 'Thorne Iron Bisglycinate', 'other',
   'Iron chelated to two glycine molecules, studied for absorption and gastrointestinal tolerability relative to iron salts.',
   'Store cool and dry.',
   'oral',
   'Commonly studied for iron deficiency correction and tolerability. This entry is the Thorne Iron Bisglycinate label as filed with the NIH Dietary Supplement Label Database.',
   array['Energy'], 'supplement', 'Thorne', 'Capsule', 'https://dsld.od.nih.gov/label/321969'),

  ('coq10', 'OL Olympian Labs Ubiquinol', 'other',
   'Ubiquinone, an electron carrier in the mitochondrial respiratory chain and a lipid-soluble antioxidant.',
   'Store cool and dry. Protect from light.',
   'oral',
   'Commonly studied for statin-associated muscle symptoms and cardiovascular outcomes. This entry is the OL Olympian Labs Ubiquinol label as filed with the NIH Dietary Supplement Label Database.',
   array['Energy', 'Anti-Aging'], 'supplement', 'OL Olympian Labs', 'Softgel Capsule', 'https://dsld.od.nih.gov/label/9928'),

  ('omega-3', 'DEVA Vegan Omega-3 DHA-EPA', 'other',
   'Long-chain marine fatty acids incorporated into cell membranes and converted to specialised pro-resolving mediators.',
   'Refrigerate after opening. Protect from light.',
   'oral',
   'Commonly studied for triglycerides, inflammatory markers and cognitive outcomes. This entry is the DEVA Vegan Omega-3 DHA-EPA label as filed with the NIH Dietary Supplement Label Database.',
   array['Focus', 'Recovery', 'Anti-Aging'], 'supplement', 'DEVA', 'Capsule', 'https://dsld.od.nih.gov/label/304315'),

  ('citicoline', 'AOR Advanced Orthomolecular Research Citicoline', 'cognitive',
   'CDP-choline, an intermediate in phosphatidylcholine synthesis, studied for membrane phospholipid turnover in neurons.',
   'Store cool and dry.',
   'oral',
   'Commonly studied for attention and memory outcomes in healthy and post-stroke populations. This entry is the AOR Advanced Orthomolecular Research Citicoline label as filed with the NIH Dietary Supplement Label Database.',
   array['Focus'], 'supplement', 'AOR Advanced Orthomolecular Research', 'Capsule', 'https://dsld.od.nih.gov/label/305918'),

  ('bacopa-monnieri', 'SuperSmart Bacopa Monnieri', 'cognitive',
   'A herb whose bacoside constituents are studied for cholinergic signalling and antioxidant activity in neural tissue.',
   'Store cool and dry.',
   'oral',
   'Commonly studied for memory acquisition over multi-week periods rather than acutely. This entry is the SuperSmart Bacopa Monnieri label as filed with the NIH Dietary Supplement Label Database.',
   array['Focus', 'Mood'], 'supplement', 'SuperSmart', 'Capsule', 'https://dsld.od.nih.gov/label/250150'),

  ('rhodiola-rosea', 'Nutracraft Rhodiola Rosea', 'cognitive',
   'An adaptogenic root whose rosavin and salidroside constituents are studied for stress-axis and monoamine signalling.',
   'Store cool and dry.',
   'oral',
   'Commonly studied for fatigue under stress and for mental performance. This entry is the Nutracraft Rhodiola Rosea label as filed with the NIH Dietary Supplement Label Database.',
   array['Focus', 'Mood', 'Energy'], 'supplement', 'Nutracraft', 'Capsule', 'https://dsld.od.nih.gov/label/246565'),

  ('whey-protein', 'Biochem 100% Whey Isolate Protein Chocolate Peppermint', 'growth',
   'A fast-digesting milk protein fraction high in leucine, studied for stimulating muscle protein synthesis.',
   'Store cool and dry.',
   'oral',
   'Commonly studied for lean mass and strength gains alongside resistance training. This entry is the Biochem 100% Whey Isolate Protein Chocolate Peppermint label as filed with the NIH Dietary Supplement Label Database.',
   array['Muscle', 'Recovery'], 'supplement', 'Biochem', 'Powder', 'https://dsld.od.nih.gov/label/258811'),

  ('beta-alanine', 'NOW Sports Beta-Alanine Powder', 'growth',
   'A precursor to carnosine, studied for raising intramuscular carnosine and buffering hydrogen ions during high-intensity effort.',
   'Store cool and dry.',
   'oral',
   'Commonly studied for performance in efforts lasting roughly one to four minutes. This entry is the NOW Sports Beta-Alanine Powder label as filed with the NIH Dietary Supplement Label Database.',
   array['Muscle', 'Energy'], 'supplement', 'NOW Sports', 'Powder', 'https://dsld.od.nih.gov/label/314248'),

  ('l-citrulline', 'NutraKey Health Performance L-Citrulline Malate', 'growth',
   'An amino acid converted to arginine in the kidney, studied for nitric oxide availability and blood flow.',
   'Store cool and dry.',
   'oral',
   'Commonly studied for exercise performance and vascular measures. This entry is the NutraKey Health Performance L-Citrulline Malate label as filed with the NIH Dietary Supplement Label Database.',
   array['Muscle', 'Recovery'], 'supplement', 'NutraKey Health Performance', 'Powder', 'https://dsld.od.nih.gov/label/240137'),

  ('vitamin-d3', 'Protocol For Life Balance High Potency D3 10,000 IU Cholecalciferol', 'other',
   'Cholecalciferol, converted in liver and kidney to the active hormone that regulates calcium handling and immune gene expression.',
   'Store cool and dry. Protect from light.',
   'oral',
   'Commonly studied for bone, muscle function and respiratory infection outcomes. This entry is the Protocol For Life Balance High Potency D3 10,000 IU Cholecalciferol label as filed with the NIH Dietary Supplement Label Database.',
   array['Muscle', 'Immune', 'Recovery'], 'supplement', 'Protocol For Life Balance', 'Capsule', 'https://dsld.od.nih.gov/label/72917'),

  ('zinc', 'AOR Advanced Orthomolecular Research Premium Zinc-Copper Balance', 'other',
   'An essential trace mineral and cofactor for hundreds of enzymes, studied for innate immune signalling and epithelial integrity.',
   'Store cool and dry.',
   'oral',
   'Commonly studied for common cold duration, taste and skin outcomes. This entry is the AOR Advanced Orthomolecular Research Premium Zinc-Copper Balance label as filed with the NIH Dietary Supplement Label Database.',
   array['Immune', 'Skin'], 'supplement', 'AOR Advanced Orthomolecular Research Premium', 'Capsule', 'https://dsld.od.nih.gov/label/214713'),

  ('elderberry', 'Nobi Nutrition Sambucus Elderberry', 'other',
   'Sambucus nigra fruit extract whose anthocyanins are studied for effects on viral entry and cytokine response in vitro.',
   'Store cool and dry. Protect from light.',
   'oral',
   'Commonly studied for upper respiratory symptom duration. This entry is the Nobi Nutrition Sambucus Elderberry label as filed with the NIH Dietary Supplement Label Database.',
   array['Immune'], 'supplement', 'Nobi Nutrition', 'Capsule', 'https://dsld.od.nih.gov/label/246787'),

  ('probiotics', 'Allergy Research Group Lactobacillus', 'other',
   'Live micro-organisms studied for effects on gut barrier function and mucosal immune signalling, with effects generally strain-specific.',
   'Refrigerate. Check the label — many strains require it.',
   'oral',
   'Commonly studied for antibiotic-associated diarrhoea and gut symptom outcomes. This entry is the Allergy Research Group Lactobacillus label as filed with the NIH Dietary Supplement Label Database.',
   array['Immune', 'Gut Health'], 'supplement', 'Allergy Research Group', 'Capsule', 'https://dsld.od.nih.gov/label/233241'),

  ('selenium', 'Pure Encapsulations Selenium (Selenomethionine)', 'other',
   'A trace mineral incorporated into selenoproteins including glutathione peroxidase, studied for antioxidant defence and thyroid metabolism.',
   'Store cool and dry.',
   'oral',
   'Commonly studied for thyroid autoimmunity and immune function, with a narrow window between deficiency and excess. This entry is the Pure Encapsulations Selenium (Selenomethionine) label as filed with the NIH Dietary Supplement Label Database.',
   array['Immune', 'Anti-Aging'], 'supplement', 'Pure Encapsulations', 'Capsule', 'https://dsld.od.nih.gov/label/184923'),

  ('oligopeptide-1-egf', 'Oligopeptide-1 (EGF)', 'cosmetic',
   'Human epidermal growth factor, studied for keratinocyte proliferation and wound epithelialisation.',
   'Refrigerate. Protect from light.',
   'topical',
   'Commonly studied for wound healing and, in cosmetic formulation research, for photoaged skin.',
   array['Skin', 'Anti-Aging'], 'peptide', null, null, null),

  ('syn-ake', 'Syn-Ake', 'cosmetic',
   'A synthetic tripeptide modelled on a component of temple viper venom, studied for nicotinic acetylcholine receptor antagonism in skin.',
   'Store cool and dry. Protect from light.',
   'topical',
   'Commonly studied in cosmetic formulation research for expression-line appearance.',
   array['Skin', 'Anti-Aging'], 'peptide', null, null, null),

  ('cortagen', 'Cortagen', 'cognitive',
   'A short synthetic peptide from the Khavinson bioregulator series, studied for effects on cortical and peripheral nerve tissue.',
   'Refrigerate. Protect from light.',
   'injected',
   'Studied largely within a single Russian research programme; the wider literature is thin.',
   array['Sleep', 'Focus'], 'peptide', null, null, null),

  ('vesugen', 'Vesugen', 'other',
   'A tripeptide from the Khavinson series, studied for effects on vascular endothelial tissue.',
   'Refrigerate. Protect from light.',
   'injected',
   'Studied largely within a single Russian research programme; the wider literature is thin.',
   array['Sleep', 'Anti-Aging'], 'peptide', null, null, null),

  ('carnosine', 'Carnosine', 'other',
   'A dipeptide of beta-alanine and histidine concentrated in muscle and brain, studied for pH buffering and carbonyl quenching.',
   'Store cool and dry.',
   'oral',
   'Commonly studied for exercise buffering capacity and for glycation markers.',
   array['Energy', 'Anti-Aging', 'Muscle'], 'peptide', null, null, null),

  ('glutathione', 'Glutathione', 'other',
   'A tripeptide of glutamate, cysteine and glycine, the principal intracellular antioxidant and a substrate for detoxification enzymes.',
   'Refrigerate. Protect from light.',
   'oral',
   'Commonly studied for oxidative stress markers, with oral bioavailability a recurring question.',
   array['Energy', 'Immune', 'Anti-Aging'], 'peptide', null, null, null),

  ('na-selank-amidate', 'NA-Selank Amidate', 'cognitive',
   'An amidated derivative of Selank, studied for a longer plasma half-life than the parent peptide.',
   'Refrigerate. Protect from light.',
   'nasal',
   'Follows the Selank literature on anxiolytic and neurotrophic signalling; direct studies of the derivative are limited.',
   array['Focus', 'Mood'], 'peptide', null, null, null),

  ('livagen', 'Livagen', 'cognitive',
   'A tetrapeptide from the Khavinson series, studied for chromatin decondensation and gene activation in lymphocytes.',
   'Refrigerate. Protect from light.',
   'injected',
   'Studied largely within a single Russian research programme; the wider literature is thin.',
   array['Focus', 'Anti-Aging'], 'peptide', null, null, null),

  ('follistatin-344', 'Follistatin-344', 'growth',
   'A glycoprotein that binds and inhibits myostatin and other TGF-beta family members, studied for effects on muscle mass regulation.',
   'Refrigerate. Protect from light.',
   'injected',
   'Commonly studied preclinically for myostatin inhibition and muscle hypertrophy.',
   array['Muscle', 'Recovery'], 'peptide', null, null, null),

  ('igf-1-lr3', 'IGF-1 LR3', 'growth',
   'A modified analogue of insulin-like growth factor 1 with reduced binding-protein affinity, studied for a longer active half-life.',
   'Refrigerate. Protect from light.',
   'injected',
   'Studied mainly as a cell-culture reagent; human data comes from the parent IGF-1 literature.',
   array['Muscle', 'Recovery'], 'peptide', null, null, null),

  ('thymalin', 'Thymalin', 'healing',
   'A polypeptide complex extracted from thymic tissue, studied for T-lymphocyte differentiation and immune restoration.',
   'Refrigerate. Protect from light.',
   'injected',
   'Commonly studied for immune parameters in older populations, largely in the Russian literature.',
   array['Immune', 'Anti-Aging'], 'peptide', null, null, null),

  ('thymogen', 'Thymogen', 'healing',
   'A synthetic dipeptide derived from thymopoietin, studied for immune cell signalling.',
   'Refrigerate. Protect from light.',
   'nasal',
   'Studied for immune parameters and mucosal immunity, largely in the Russian literature.',
   array['Immune', 'Gut Health'], 'peptide', null, null, null)
on conflict (slug) do update set
  name = excluded.name, brand = excluded.brand, product_form = excluded.product_form,
  label_url = excluded.label_url, kind = excluded.kind, goal_tags = excluded.goal_tags,
  research_summary = excluded.research_summary;

-- ── articles: five per entry ──────────────────────────────────────────
insert into public.glossary_research (glossary_id, title, meta, url)
select g.id, t.title, t.meta, t.url
from public.glossary g
join (values
  ('collagen-peptides', 'Skin Anti-Aging and Moisturizing Effects of Low-Molecular-Weight Collagen Peptide Supplementation in Healthy Adults: A Randomized, Double-Blind, Placebo-Controlled Clinical Trial', '1/5 · Efficacy · J Microbiol Biotechnol, 2025', 'https://pubmed.ncbi.nlm.nih.gov/40935395/'),
  ('collagen-peptides', 'Molecular Mechanisms of Dermal Aging and Antiaging Approaches', '2/5 · Mechanism · Int J Mol Sci, 2019', 'https://pubmed.ncbi.nlm.nih.gov/31036793/'),
  ('collagen-peptides', 'Effects of Resmetirom on Noninvasive Endpoints in a 36-Week Phase 2 Active Treatment Extension Study in Patients With NASH', '3/5 · Safety · Hepatol Commun, 2021', 'https://pubmed.ncbi.nlm.nih.gov/33860116/'),
  ('collagen-peptides', 'The Effects of Collagen Peptides as a Dietary Supplement on Muscle Damage Recovery and Fatigue Responses: An Integrative Review', '4/5 · Practical · Nutrients, 2024', 'https://pubmed.ncbi.nlm.nih.gov/39408370/'),
  ('collagen-peptides', 'TANGO1 inhibitors reduce collagen secretion and limit tissue scarring', '5/5 · Interactions · Nat Commun, 2024', 'https://pubmed.ncbi.nlm.nih.gov/38658535/'),
  ('biotin', 'A Review of the Use of Biotin for Hair Loss', '1/5 · Efficacy · Skin Appendage Disord, 2017', 'https://pubmed.ncbi.nlm.nih.gov/28879195/'),
  ('biotin', 'Hormone Immunoassay Interference: A 2021 Update', '2/5 · Safety · Ann Lab Med, 2022', 'https://pubmed.ncbi.nlm.nih.gov/34374345/'),
  ('biotin', 'Comparative bioavailability of vitamins in human foods sourced from animals and plants', '3/5 · Practical · Crit Rev Food Sci Nutr, 2024', 'https://pubmed.ncbi.nlm.nih.gov/37522617/'),
  ('biotin', 'Biotin: From Nutrition to Therapeutics', '4/5 · Interactions · J Nutr, 2017', 'https://pubmed.ncbi.nlm.nih.gov/28701385/'),
  ('biotin', 'High-dose biotin for multiple sclerosis: A systematic review and meta-analyses of randomized controlled trials', '5/5 · Further reading · Mult Scler Relat Disord, 2021', 'https://pubmed.ncbi.nlm.nih.gov/34332461/'),
  ('vitamin-c', 'The Effects of Dietary Supplementation with Collagen and Vitamin C and Their Combination with Hyaluronic Acid on Skin Density, Texture and Other Parameters: A Randomised, Double-Blind, Placebo-Controlled Trial', '1/5 · Efficacy · Nutrients, 2024', 'https://pubmed.ncbi.nlm.nih.gov/38931263/'),
  ('vitamin-c', 'Induction of collagen synthesis by ascorbic acid. A possible mechanism', '2/5 · Mechanism · Arch Dermatol, 1987', 'https://pubmed.ncbi.nlm.nih.gov/2825607/'),
  ('vitamin-c', 'Market analysis of vitamin C-containing dietary supplements in Germany and the USA: Consumer information and risks and benefits', '3/5 · Safety · Naunyn Schmiedebergs Arch Pharmacol, 2025', 'https://pubmed.ncbi.nlm.nih.gov/40381012/'),
  ('vitamin-c', 'Demonstration of saturation kinetics in the intestinal absorption of vitamin C in man and the guinea pig', '4/5 · Practical · J Clin Pharmacol, 1978', 'https://pubmed.ncbi.nlm.nih.gov/209065/'),
  ('vitamin-c', 'Interaction of vitamin C and iron', '5/5 · Interactions · Ann N Y Acad Sci, 1980', 'https://pubmed.ncbi.nlm.nih.gov/6940487/'),
  ('hyaluronic-acid', 'Oral Hyaluronic Acid Supplement: Efficacy in Skin Hydration, Elasticity, and Wrinkle Depth Reduction', '1/5 · Efficacy · J Drugs Dermatol, 2025', 'https://pubmed.ncbi.nlm.nih.gov/40911749/'),
  ('hyaluronic-acid', 'Hyaluronic acid and HA-modified cationic liposomes for promoting skin penetration and retention', '2/5 · Mechanism · J Control Release, 2023', 'https://pubmed.ncbi.nlm.nih.gov/37004799/'),
  ('hyaluronic-acid', 'A Multicenter, Randomized, Double-Blinded, Placebo-Controlled Clinical Trial to Evaluate the Efficacy and Safety of a Krill Oil, Astaxanthin, and Oral Hyaluronic Acid Complex on Joint Health in People with Mild Osteoarthritis', '3/5 · Safety · Nutrients, 2023', 'https://pubmed.ncbi.nlm.nih.gov/37686801/'),
  ('hyaluronic-acid', 'Steady state plasma and tissue distribution of low molecular weight hyaluronic acid after oral administration in mice', '4/5 · Practical · Nat Prod Res, 2024', 'https://pubmed.ncbi.nlm.nih.gov/37081790/'),
  ('hyaluronic-acid', 'OARSI guidelines for the non-surgical management of knee, hip, and polyarticular osteoarthritis', '5/5 · Interactions · Osteoarthritis Cartilage, 2019', 'https://pubmed.ncbi.nlm.nih.gov/31278997/'),
  ('magnesium-glycinate', 'The Role of Magnesium in Sleep Health: a Systematic Review of Available Literature', '1/5 · Efficacy · Biol Trace Elem Res, 2023', 'https://pubmed.ncbi.nlm.nih.gov/35184264/'),
  ('magnesium-glycinate', 'Magnesium in schizophrenia', '2/5 · Mechanism · Pharmacol Rep, 2017', 'https://pubmed.ncbi.nlm.nih.gov/28651118/'),
  ('magnesium-glycinate', 'Perspective: Call for Re-evaluation of the Tolerable Upper Intake Level for Magnesium Supplementation in Adults', '3/5 · Safety · Adv Nutr, 2023', 'https://pubmed.ncbi.nlm.nih.gov/37487817/'),
  ('magnesium-glycinate', 'Orlistat-associated adverse effects and drug interactions: a critical review', '4/5 · Interactions · Drug Saf, 2008', 'https://pubmed.ncbi.nlm.nih.gov/18095746/'),
  ('magnesium-glycinate', 'Bioavailability of magnesium diglycinate vs magnesium oxide in patients with ileal resection', '5/5 · Further reading · JPEN J Parenter Enteral Nutr, 1994', 'https://pubmed.ncbi.nlm.nih.gov/7815675/'),
  ('melatonin', 'Meta-analysis: melatonin for the treatment of primary sleep disorders', '1/5 · Efficacy · PLoS One, 2013', 'https://pubmed.ncbi.nlm.nih.gov/23691095/'),
  ('melatonin', 'Circadian rhythms in lizards: phase response curve for melatonin', '2/5 · Mechanism · J Pineal Res, 1986', 'https://pubmed.ncbi.nlm.nih.gov/3723331/'),
  ('melatonin', 'Comparative effects of pharmacological interventions for the acute and long-term management of insomnia disorder in adults: a systematic review and network meta-analysis', '3/5 · Safety · Lancet, 2022', 'https://pubmed.ncbi.nlm.nih.gov/35843245/'),
  ('melatonin', 'Circadian Rhythm Sleep-Wake Phase Disorders', '4/5 · Practical · Neurol Clin, 2019', 'https://pubmed.ncbi.nlm.nih.gov/31256787/'),
  ('melatonin', 'Potential drug interactions with melatonin', '5/5 · Interactions · Physiol Behav, 2014', 'https://pubmed.ncbi.nlm.nih.gov/24732412/'),
  ('l-theanine', 'Anti-Stress, Behavioural and Magnetoencephalography Effects of an L-Theanine-Based Nutrient Drink: A Randomised, Double-Blind, Placebo-Controlled, Crossover Trial', '1/5 · Efficacy · Nutrients, 2016', 'https://pubmed.ncbi.nlm.nih.gov/26797633/'),
  ('l-theanine', 'Medicinal herbs for the treatment of anxiety: A systematic review and network meta-analysis', '2/5 · Safety · Pharmacol Res, 2022', 'https://pubmed.ncbi.nlm.nih.gov/35378276/'),
  ('l-theanine', 'Effects of L-theanine-caffeine combination on sustained attention and inhibitory control among children with ADHD: a proof-of-concept neuroimaging RCT', '3/5 · Practical · Sci Rep, 2020', 'https://pubmed.ncbi.nlm.nih.gov/32753637/'),
  ('l-theanine', 'Effects of L-Theanine Administration on Stress-Related Symptoms and Cognitive Functions in Healthy Adults: A Randomized Controlled Trial', '4/5 · Interactions · Nutrients, 2019', 'https://pubmed.ncbi.nlm.nih.gov/31623400/'),
  ('l-theanine', 'The Cognitive-Enhancing Outcomes of Caffeine and L-theanine: A Systematic Review', '5/5 · Further reading · Cureus, 2021', 'https://pubmed.ncbi.nlm.nih.gov/35111479/'),
  ('glycine', 'New therapeutic strategy for amino acid medicine: glycine improves the quality of sleep', '1/5 · Mechanism · J Pharmacol Sci, 2012', 'https://pubmed.ncbi.nlm.nih.gov/22293292/'),
  ('glycine', 'Unlocking the Therapeutic Potential of Marine Collagen: A Scientific Exploration for Delaying Skin Aging', '2/5 · Safety · Mar Drugs, 2024', 'https://pubmed.ncbi.nlm.nih.gov/38667776/'),
  ('glycine', 'Vitamin C-enriched gelatin supplementation before intermittent activity augments collagen synthesis', '3/5 · Interactions · Am J Clin Nutr, 2017', 'https://pubmed.ncbi.nlm.nih.gov/27852613/'),
  ('glycine', 'The effect of glycine administration on the characteristics of physiological systems in human adults: A systematic review', '4/5 · Further reading · Geroscience, 2024', 'https://pubmed.ncbi.nlm.nih.gov/37851316/'),
  ('glycine', 'The effects of oral ferrous bisglycinate supplementation on hemoglobin and ferritin concentrations in adults and children: a systematic review and meta-analysis of randomized controlled trials', '5/5 · Further reading · Nutr Rev, 2023', 'https://pubmed.ncbi.nlm.nih.gov/36728680/'),
  ('creatine-monohydrate', 'Creatine monohydrate for lean mass, strength, and bone density in postmenopausal women: a systematic review and meta-analysis', '1/5 · Efficacy · J Int Soc Sports Nutr, 2026', 'https://pubmed.ncbi.nlm.nih.gov/42141930/'),
  ('creatine-monohydrate', 'Creatine supplementation and endurance performance: surges and sprints to win the race', '2/5 · Mechanism · J Int Soc Sports Nutr, 2023', 'https://pubmed.ncbi.nlm.nih.gov/37096381/'),
  ('creatine-monohydrate', 'The effect of creatine supplementation on kidney function: a systematic review and meta-analysis of randomized controlled trials', '3/5 · Safety · J Ren Nutr, 2026', 'https://pubmed.ncbi.nlm.nih.gov/42035842/'),
  ('creatine-monohydrate', 'Timing of Creatine Supplementation around Exercise: A Real Concern?', '4/5 · Practical · Nutrients, 2021', 'https://pubmed.ncbi.nlm.nih.gov/34445003/'),
  ('creatine-monohydrate', 'Single dose creatine improves cognitive performance and induces changes in cerebral high energy phosphates during sleep deprivation', '5/5 · Interactions · Sci Rep, 2024', 'https://pubmed.ncbi.nlm.nih.gov/38418482/'),
  ('vitamin-b12', 'Vitamin B12 Supplementation in Diabetic Neuropathy: A 1-Year, Randomized, Double-Blind, Placebo-Controlled Trial', '1/5 · Efficacy · Nutrients, 2021', 'https://pubmed.ncbi.nlm.nih.gov/33513879/'),
  ('vitamin-b12', 'Homocysteine and Hyperhomocysteinaemia', '2/5 · Mechanism · Curr Med Chem, 2019', 'https://pubmed.ncbi.nlm.nih.gov/29532755/'),
  ('vitamin-b12', 'Proton Pump Inhibitors (PPIs)-An Evidence-Based Review of Indications, Efficacy, Harms, and Deprescribing', '3/5 · Safety · Medicina (Kaunas), 2025', 'https://pubmed.ncbi.nlm.nih.gov/41010960/'),
  ('vitamin-b12', 'Efficacy of sublingual and oral vitamin B12 versus intramuscular administration: insights from a systematic review and meta-analysis', '4/5 · Practical · Front Pharmacol, 2025', 'https://pubmed.ncbi.nlm.nih.gov/41487531/'),
  ('vitamin-b12', 'Long-Term Use of Metformin and Vitamin B12 Deficiency in Diabetes', '5/5 · Interactions · Curr Drug Saf, 2025', 'https://pubmed.ncbi.nlm.nih.gov/39206482/'),
  ('iron-bisglycinate', 'Low-Dose Prophylactic Oral Iron Supplementation (Ferrous Fumarate, Ferrous Bisglycinate, and Ferrous Sulphate) in Pregnancy Is Not Associated With Clinically Significant Gastrointestinal Complaints: Results From Two Randomized Studies', '1/5 · Efficacy · J Pregnancy, 2024', 'https://pubmed.ncbi.nlm.nih.gov/39582678/'),
  ('iron-bisglycinate', 'Iron considerations for the athlete: a narrative review', '2/5 · Mechanism · Eur J Appl Physiol, 2019', 'https://pubmed.ncbi.nlm.nih.gov/31055680/'),
  ('iron-bisglycinate', 'Tolerability of different oral iron supplements: a systematic review', '3/5 · Safety · Curr Med Res Opin, 2013', 'https://pubmed.ncbi.nlm.nih.gov/23252877/'),
  ('iron-bisglycinate', 'Iron absorption from supplements is greater with alternate day than with consecutive day dosing in iron-deficient anemic women', '4/5 · Practical · Haematologica, 2020', 'https://pubmed.ncbi.nlm.nih.gov/31413088/'),
  ('iron-bisglycinate', 'Orlistat-associated adverse effects and drug interactions: a critical review', '5/5 · Interactions · Drug Saf, 2008', 'https://pubmed.ncbi.nlm.nih.gov/18095746/'),
  ('coq10', 'Effects of Coenzyme Q10 Supplementation on Lipid Profiles in Adults: A Meta-analysis of Randomized Controlled Trials', '1/5 · Efficacy · J Clin Endocrinol Metab, 2022', 'https://pubmed.ncbi.nlm.nih.gov/36337001/'),
  ('coq10', 'The Effect of CoQ10 supplementation on ART treatment and oocyte quality in older women', '2/5 · Mechanism · Hum Fertil (Camb), 2023', 'https://pubmed.ncbi.nlm.nih.gov/37102567/'),
  ('coq10', 'Efficacy and safety of coenzyme Q10 in heart failure: a meta-analysis of randomized controlled trials', '3/5 · Safety · BMC Cardiovasc Disord, 2024', 'https://pubmed.ncbi.nlm.nih.gov/39462324/'),
  ('coq10', 'Bioavailability of coenzyme Q10 supplements depends on carrier lipids and solubilization', '4/5 · Practical · Nutrition, 2019', 'https://pubmed.ncbi.nlm.nih.gov/30153575/'),
  ('coq10', 'Nutrition and bipolar disorder: a systematic review', '5/5 · Further reading · Nutr Neurosci, 2023', 'https://pubmed.ncbi.nlm.nih.gov/35608150/'),
  ('omega-3', 'Lutein + zeaxanthin and omega-3 fatty acids for age-related macular degeneration: the Age-Related Eye Disease Study 2 (AREDS2) randomized clinical trial', '1/5 · Efficacy · JAMA, 2013', 'https://pubmed.ncbi.nlm.nih.gov/23644932/'),
  ('omega-3', 'Pro-resolving lipid mediators are leads for resolution physiology', '2/5 · Mechanism · Nature, 2014', 'https://pubmed.ncbi.nlm.nih.gov/24899309/'),
  ('omega-3', 'Efficacy and Safety of Omega-3 Fatty Acids in the Prevention of Cardiovascular Disease: A Systematic Review and Meta-analysis', '3/5 · Safety · Cardiovasc Drugs Ther, 2024', 'https://pubmed.ncbi.nlm.nih.gov/36103100/'),
  ('omega-3', 'Strategies to improve bioavailability of omega-3 fatty acids from ethyl ester concentrates', '4/5 · Practical · Curr Opin Clin Nutr Metab Care, 2019', 'https://pubmed.ncbi.nlm.nih.gov/30550388/'),
  ('omega-3', 'Marine omega-3 phospholipids: metabolism and biological activities', '5/5 · Interactions · Int J Mol Sci, 2012', 'https://pubmed.ncbi.nlm.nih.gov/23203133/'),
  ('citicoline', 'Use of Citicoline in Attention-Deficit/Hyperactivity Disorder: A Pilot Study', '1/5 · Efficacy · Clin Neuropharmacol, 2024', 'https://pubmed.ncbi.nlm.nih.gov/38976279/'),
  ('citicoline', 'Phosphatidylcholine and the CDP-choline cycle', '2/5 · Mechanism · Biochim Biophys Acta, 2013', 'https://pubmed.ncbi.nlm.nih.gov/23010477/'),
  ('citicoline', 'Ketamine and other glutamate receptor modulators for depression in adults with unipolar major depressive disorder', '3/5 · Safety · Cochrane Database Syst Rev, 2021', 'https://pubmed.ncbi.nlm.nih.gov/34510411/'),
  ('citicoline', 'The role of citicoline in cognitive impairment: pharmacological characteristics, possible advantages, and doubts for an old drug with new perspectives', '4/5 · Practical · Clin Interv Aging, 2015', 'https://pubmed.ncbi.nlm.nih.gov/26366063/'),
  ('citicoline', 'Citicoline: pharmacological and clinical review, 2022 update', '5/5 · Interactions · Rev Neurol, 2022', 'https://pubmed.ncbi.nlm.nih.gov/36544369/'),
  ('bacopa-monnieri', 'Effects of a standardized Bacopa monnieri extract on cognitive performance, anxiety, and depression in the elderly: a randomized, double-blind, placebo-controlled trial', '1/5 · Efficacy · J Altern Complement Med, 2008', 'https://pubmed.ncbi.nlm.nih.gov/18611150/'),
  ('bacopa-monnieri', 'Translational potential of medicinal plants for Alzheimer''s disease: integrated evidence from molecular mechanisms to preclinical and clinical findings', '2/5 · Mechanism · Nat Prod Bioprospect, 2026', 'https://pubmed.ncbi.nlm.nih.gov/42406197/'),
  ('bacopa-monnieri', 'Harder, better, faster, stronger? Retrospective chart review of adverse events of interactions between adaptogens and antidepressant drugs', '3/5 · Safety · Front Pharmacol, 2023', 'https://pubmed.ncbi.nlm.nih.gov/37829299/'),
  ('bacopa-monnieri', 'Plant-derived nootropics and human cognition: A systematic review', '4/5 · Interactions · Crit Rev Food Sci Nutr, 2023', 'https://pubmed.ncbi.nlm.nih.gov/34978226/'),
  ('bacopa-monnieri', 'Investigating the Neuroprotective and Cognitive-Enhancing Effects of Bacopa monnieri: A Systematic Review Focused on Inflammation, Oxidative Stress, Mitochondrial Dysfunction, and Apoptosis', '5/5 · Further reading · Antioxidants (Basel), 2024', 'https://pubmed.ncbi.nlm.nih.gov/38671841/'),
  ('rhodiola-rosea', 'A randomised, double-blind, placebo-controlled, parallel-group study of the standardised extract shr-5 of the roots of Rhodiola rosea in the treatment of subjects with stress-related fatigue', '1/5 · Efficacy · Planta Med, 2009', 'https://pubmed.ncbi.nlm.nih.gov/19016404/'),
  ('rhodiola-rosea', 'Rhodiola rosea as an adaptogen to enhance exercise performance: a review of the literature', '2/5 · Mechanism · Br J Nutr, 2024', 'https://pubmed.ncbi.nlm.nih.gov/37641937/'),
  ('rhodiola-rosea', 'The Effects of Rhodiola rosea L. Extract on Anxiety, Stress, Cognition and Other Mood Symptoms', '3/5 · Safety · Phytother Res, 2015', 'https://pubmed.ncbi.nlm.nih.gov/26502953/'),
  ('rhodiola-rosea', 'The Effectiveness of Rhodiola rosea L. Preparations in Alleviating Various Aspects of Life-Stress Symptoms and Stress-Induced Conditions-Encouraging Clinical Evidence', '4/5 · Interactions · Molecules, 2022', 'https://pubmed.ncbi.nlm.nih.gov/35745023/'),
  ('rhodiola-rosea', 'Effects of Rhodiola Rosea Supplementation on Exercise and Sport: A Systematic Review', '5/5 · Further reading · Front Nutr, 2022', 'https://pubmed.ncbi.nlm.nih.gov/35464040/'),
  ('whey-protein', 'A systematic review, meta-analysis and meta-regression of the effect of protein supplementation on resistance training-induced gains in muscle mass and strength in healthy adults', '1/5 · Efficacy · Br J Sports Med, 2018', 'https://pubmed.ncbi.nlm.nih.gov/28698222/'),
  ('whey-protein', 'Enhancing Muscle Quality: Exploring Leucine and Whey Protein in Sarcopenic Individuals', '2/5 · Mechanism · J Cachexia Sarcopenia Muscle, 2025', 'https://pubmed.ncbi.nlm.nih.gov/40937507/'),
  ('whey-protein', 'Protein quality and safety evaluation of sarcoplasmic protein derived from silver carp (Hypophthalmichthys molitrix) using a rat model', '3/5 · Safety · J Food Sci, 2020', 'https://pubmed.ncbi.nlm.nih.gov/32632919/'),
  ('whey-protein', 'Nutrient timing revisited: is there a post-exercise anabolic window?', '4/5 · Practical · J Int Soc Sports Nutr, 2013', 'https://pubmed.ncbi.nlm.nih.gov/23360586/'),
  ('whey-protein', 'Whey protein supplementation and its potentially adverse effects on health: a systematic review', '5/5 · Further reading · Appl Physiol Nutr Metab, 2021', 'https://pubmed.ncbi.nlm.nih.gov/32702243/'),
  ('beta-alanine', 'β-alanine supplementation to improve exercise capacity and performance: a systematic review and meta-analysis', '1/5 · Efficacy · Br J Sports Med, 2017', 'https://pubmed.ncbi.nlm.nih.gov/27797728/'),
  ('beta-alanine', 'International society of sports nutrition position stand: Beta-Alanine', '2/5 · Mechanism · J Int Soc Sports Nutr, 2015', 'https://pubmed.ncbi.nlm.nih.gov/26175657/'),
  ('beta-alanine', 'The Top 5 Can''t-Miss Sport Supplements', '3/5 · Safety · Nutrients, 2024', 'https://pubmed.ncbi.nlm.nih.gov/39408214/'),
  ('beta-alanine', 'Fabrication and characterization of vitamin B5 loaded poly (l-lactide-co-caprolactone)/silk fiber aligned electrospun nanofibers for schwann cell proliferation', '4/5 · Practical · Colloids Surf B Biointerfaces, 2016', 'https://pubmed.ncbi.nlm.nih.gov/27085042/'),
  ('beta-alanine', '24-Week β-alanine ingestion does not affect muscle taurine or clinical blood parameters in healthy males', '5/5 · Interactions · Eur J Nutr, 2020', 'https://pubmed.ncbi.nlm.nih.gov/30552505/'),
  ('l-citrulline', 'Effect of food sources of nitrate, polyphenols, L-arginine and L-citrulline on endurance exercise performance: a systematic review and meta-analysis of randomised controlled trials', '1/5 · Efficacy · J Int Soc Sports Nutr, 2021', 'https://pubmed.ncbi.nlm.nih.gov/34965876/'),
  ('l-citrulline', 'Supplementation with Nitric Oxide Precursors for Strength Performance: A Review of the Current Literature', '2/5 · Mechanism · Nutrients, 2023', 'https://pubmed.ncbi.nlm.nih.gov/36771366/'),
  ('l-citrulline', 'Diminished global arginine bioavailability and increased arginine catabolism as metabolic profile of increased cardiovascular risk', '3/5 · Practical · J Am Coll Cardiol, 2009', 'https://pubmed.ncbi.nlm.nih.gov/19477356/'),
  ('l-citrulline', 'NETosis Drives Blood Pressure Elevation and Vascular Dysfunction in Hypertension', '4/5 · Interactions · Circ Res, 2024', 'https://pubmed.ncbi.nlm.nih.gov/38666386/'),
  ('l-citrulline', 'Micronutrient Supplementation to Reduce Cardiovascular Risk', '5/5 · Further reading · J Am Coll Cardiol, 2022', 'https://pubmed.ncbi.nlm.nih.gov/36480969/'),
  ('vitamin-d3', 'Association between vitamin D supplementation and mortality: systematic review and meta-analysis', '1/5 · Efficacy · BMJ, 2019', 'https://pubmed.ncbi.nlm.nih.gov/31405892/'),
  ('vitamin-d3', 'Vitamin D: Metabolism, Molecular Mechanism of Action, and Pleiotropic Effects', '2/5 · Mechanism · Physiol Rev, 2016', 'https://pubmed.ncbi.nlm.nih.gov/26681795/'),
  ('vitamin-d3', 'Safety and effectiveness of vitamin D mega-dose: A systematic review', '3/5 · Safety · Clin Nutr ESPEN, 2021', 'https://pubmed.ncbi.nlm.nih.gov/34857184/'),
  ('vitamin-d3', 'Intestinal absorption of vitamin D: a systematic review', '4/5 · Practical · Nutr Rev, 2018', 'https://pubmed.ncbi.nlm.nih.gov/29025082/'),
  ('vitamin-d3', 'Comparison of vitamin D2 and vitamin D3 supplementation in raising serum 25-hydroxyvitamin D status: a systematic review and meta-analysis', '5/5 · Further reading · Am J Clin Nutr, 2012', 'https://pubmed.ncbi.nlm.nih.gov/22552031/'),
  ('zinc', 'PURLs: Zinc for the common cold--not if, but when', '1/5 · Efficacy · J Fam Pract, 2011', 'https://pubmed.ncbi.nlm.nih.gov/22049349/'),
  ('zinc', 'Zinc as a Gatekeeper of Immune Function', '2/5 · Mechanism · Nutrients, 2017', 'https://pubmed.ncbi.nlm.nih.gov/29186856/'),
  ('zinc', 'Zinc Toxicity: Understanding the Limits', '3/5 · Safety · Molecules, 2024', 'https://pubmed.ncbi.nlm.nih.gov/38999082/'),
  ('zinc', 'Iron Metabolism, Calcium, Magnesium and Trace Elements: A Review', '4/5 · Interactions · Biol Trace Elem Res, 2025', 'https://pubmed.ncbi.nlm.nih.gov/38969940/'),
  ('zinc', 'Correlation between serum zinc and testosterone: A systematic review', '5/5 · Further reading · J Trace Elem Med Biol, 2023', 'https://pubmed.ncbi.nlm.nih.gov/36577241/'),
  ('elderberry', 'Elderberry Supplementation Reduces Cold Duration and Symptoms in Air-Travellers: A Randomized, Double-Blind Placebo-Controlled Clinical Trial', '1/5 · Efficacy · Nutrients, 2016', 'https://pubmed.ncbi.nlm.nih.gov/27023596/'),
  ('elderberry', 'Elderberry Extracts: Characterization of the Polyphenolic Chemical Composition, Quality Consistency, Safety, Adulteration, and Attenuation of Oxidative Stress- and Inflammation-Induced Health Disorders', '2/5 · Mechanism · Molecules, 2023', 'https://pubmed.ncbi.nlm.nih.gov/37049909/'),
  ('elderberry', 'A novel pyrazolo [3,4-d] pyrimidine, KKC080106, activates the Nrf2 pathway and protects nigral dopaminergic neurons', '3/5 · Safety · Exp Neurol, 2020', 'https://pubmed.ncbi.nlm.nih.gov/32580013/'),
  ('elderberry', 'The effect of Sambucol, a black elderberry-based, natural product, on the production of human cytokines: I. Inflammatory cytokines', '4/5 · Practical · Eur Cytokine Netw, 2001', 'https://pubmed.ncbi.nlm.nih.gov/11399518/'),
  ('elderberry', 'Elderberry Extract Outpatient Influenza Treatment for Emergency Room Patients Ages 5 and Above: a Randomized, Double-Blind, Placebo-Controlled Trial', '5/5 · Interactions · J Gen Intern Med, 2020', 'https://pubmed.ncbi.nlm.nih.gov/32929634/'),
  ('probiotics', 'Impact of Lactobacillus crispatus-containing oral and vaginal probiotics on vaginal health: a randomised double-blind placebo controlled clinical trial', '1/5 · Efficacy · Benef Microbes, 2023', 'https://pubmed.ncbi.nlm.nih.gov/36856121/'),
  ('probiotics', 'Akkermansia muciniphila in neuropsychiatric disorders: friend or foe?', '2/5 · Mechanism · Front Cell Infect Microbiol, 2023', 'https://pubmed.ncbi.nlm.nih.gov/37492530/'),
  ('probiotics', 'Probiotics for the prevention of pediatric antibiotic-associated diarrhea', '3/5 · Safety · Cochrane Database Syst Rev, 2019', 'https://pubmed.ncbi.nlm.nih.gov/31039287/'),
  ('probiotics', 'Encapsulating Viability of Multi-strain Lactobacilli as Potential Probiotic in Pigs', '4/5 · Practical · Probiotics Antimicrob Proteins, 2019', 'https://pubmed.ncbi.nlm.nih.gov/29667009/'),
  ('probiotics', 'Probiotics for the prevention of antibiotic-associated diarrhoea: a systematic review and meta-analysis', '5/5 · Interactions · BMJ Open, 2021', 'https://pubmed.ncbi.nlm.nih.gov/34385227/'),
  ('selenium', 'Selenium Supplementation in Patients with Hashimoto Thyroiditis: A Systematic Review and Meta-Analysis of Randomized Clinical Trials', '1/5 · Efficacy · Thyroid, 2024', 'https://pubmed.ncbi.nlm.nih.gov/38243784/'),
  ('selenium', 'Mechanisms of ferroptosis', '2/5 · Mechanism · Cell Mol Life Sci, 2016', 'https://pubmed.ncbi.nlm.nih.gov/27048822/'),
  ('selenium', 'Assessing the ability of silage lactic acid bacteria to incorporate and transform inorganic selenium within laboratory scale silos', '3/5 · Practical · Anim Feed Sci Technol, 2019', 'https://pubmed.ncbi.nlm.nih.gov/31293291/'),
  ('selenium', 'Selenium and thyroid diseases', '4/5 · Interactions · Front Endocrinol (Lausanne), 2023', 'https://pubmed.ncbi.nlm.nih.gov/37033262/'),
  ('selenium', 'A systematic review of Selenium as a complementary treatment in cancer patients', '5/5 · Further reading · Complement Ther Med, 2024', 'https://pubmed.ncbi.nlm.nih.gov/39374898/'),
  ('oligopeptide-1-egf', 'Improving Diabetic Wound-Healing Outcomes With Topical Growth Factor Therapies', '1/5 · Efficacy · J Clin Endocrinol Metab, 2024', 'https://pubmed.ncbi.nlm.nih.gov/38477463/'),
  ('oligopeptide-1-egf', 'Anthralin decreases keratinocyte TGF-alpha expression and EGF-receptor binding in vitro', '2/5 · Mechanism · J Invest Dermatol, 1992', 'https://pubmed.ncbi.nlm.nih.gov/1314863/'),
  ('oligopeptide-1-egf', 'Topical Recombinant Human Epidermal Growth Factor for Diabetic Foot Ulcers: A Meta-Analysis of Randomized Controlled Clinical Trials', '3/5 · Safety · Ann Vasc Surg, 2020', 'https://pubmed.ncbi.nlm.nih.gov/31394225/'),
  ('oligopeptide-1-egf', 'Biological drug and drug delivery-mediated immunotherapy', '4/5 · Practical · Acta Pharm Sin B, 2021', 'https://pubmed.ncbi.nlm.nih.gov/33996408/'),
  ('oligopeptide-1-egf', 'The influence of retinol concentration in liquid crystal formula on epidermal growth factor, interleukin-6 and transglutaminase-1 mRNA expression in the epidermis', '5/5 · Interactions · J Physiol Pharmacol, 2020', 'https://pubmed.ncbi.nlm.nih.gov/32350151/'),
  ('syn-ake', 'Enhancement by calcitonin gene-related peptide of nicotinic receptor-operated noncontractile Ca2+ mobilization at the mouse neuromuscular junction', '1/5 · Mechanism · Br J Pharmacol, 1993', 'https://pubmed.ncbi.nlm.nih.gov/8242236/'),
  ('syn-ake', 'Long-Term Treatment of Atopic Dermatitis', '2/5 · Safety · Dermatol Clin, 2017', 'https://pubmed.ncbi.nlm.nih.gov/28577803/'),
  ('syn-ake', 'Acetyl Hexapeptide-8 in Cosmeceuticals-A Review of Skin Permeability and Efficacy', '3/5 · Practical · Int J Mol Sci, 2025', 'https://pubmed.ncbi.nlm.nih.gov/40565185/'),
  ('syn-ake', 'Anti-Wrinkle Benefits of Peptides Complex Stimulating Skin Basement Membrane Proteins Expression', '4/5 · Interactions · Int J Mol Sci, 2019', 'https://pubmed.ncbi.nlm.nih.gov/31861912/'),
  ('syn-ake', 'Cosmeceuticals in photoaging: A review', '5/5 · Further reading · Skin Res Technol, 2024', 'https://pubmed.ncbi.nlm.nih.gov/39233460/'),
  ('cortagen', 'Peptide Regulation of Gene Expression: A Systematic Review', '1/5 · Efficacy · Molecules, 2021', 'https://pubmed.ncbi.nlm.nih.gov/34834147/'),
  ('cortagen', 'Regulation of fungal gene expression via short open reading frames in the mRNA 5''untranslated region', '2/5 · Mechanism · Mol Microbiol, 2003', 'https://pubmed.ncbi.nlm.nih.gov/12890013/'),
  ('cortagen', 'DOCK2 is involved in the host genetics and biology of severe COVID-19', '3/5 · Safety · Nature, 2022', 'https://pubmed.ncbi.nlm.nih.gov/35940203/'),
  ('cortagen', 'Peptides Regulating Proliferative Activity and Inflammatory Pathways in the Monocyte/Macrophage THP-1 Cell Line', '4/5 · Practical · Int J Mol Sci, 2022', 'https://pubmed.ncbi.nlm.nih.gov/35408963/'),
  ('cortagen', 'Studies of cytokines in nerve tissue cultures', '5/5 · Interactions · Neurosci Behav Physiol, 2000', 'https://pubmed.ncbi.nlm.nih.gov/10970020/'),
  ('vesugen', '[Epigenetic aspects of peptidergic regulation of vascular endothelial cell proliferation during aging]', '1/5 · Efficacy · Adv Gerontol, 2014', 'https://pubmed.ncbi.nlm.nih.gov/25051766/'),
  ('vesugen', 'CX3CL1/CX3CR1 interaction protects against lipotoxicity-induced nonalcoholic steatohepatitis by regulating macrophage migration and M1/M2 status', '2/5 · Mechanism · Metabolism, 2022', 'https://pubmed.ncbi.nlm.nih.gov/35914622/'),
  ('vesugen', 'Injectable Peptide Therapy: A Primer for Orthopaedic and Sports Medicine Physicians', '3/5 · Safety · Am J Sports Med, 2026', 'https://pubmed.ncbi.nlm.nih.gov/41476424/'),
  ('vesugen', 'Effects of Vascular Peptide Bioregulator on the Density of Microvascular Network in the Brain Cortex of Aged Rats', '4/5 · Practical · Bull Exp Biol Med, 2016', 'https://pubmed.ncbi.nlm.nih.gov/27383168/'),
  ('vesugen', 'Advanced application of stimuli-responsive drug delivery system for inflammatory arthritis treatment', '5/5 · Interactions · Mater Today Bio, 2022', 'https://pubmed.ncbi.nlm.nih.gov/35243298/'),
  ('carnosine', 'β-alanine supplementation to improve exercise capacity and performance: a systematic review and meta-analysis', '1/5 · Efficacy · Br J Sports Med, 2017', 'https://pubmed.ncbi.nlm.nih.gov/27797728/'),
  ('carnosine', 'Acrolein-sequestering ability of endogenous dipeptides: characterization of carnosine and homocarnosine/acrolein adducts by electrospray ionization tandem mass spectrometry', '2/5 · Mechanism · J Mass Spectrom, 2003', 'https://pubmed.ncbi.nlm.nih.gov/14505328/'),
  ('carnosine', 'Dietary Carnosine Supplementation in Healthy Human Volunteers: A Safety, Tolerability, Plasma and Brain Concentration Study', '3/5 · Safety · Nutrients, 2025', 'https://pubmed.ncbi.nlm.nih.gov/40647235/'),
  ('carnosine', 'Acute balenine supplementation in humans as a natural carnosinase-resistant alternative to carnosine', '4/5 · Practical · Sci Rep, 2023', 'https://pubmed.ncbi.nlm.nih.gov/37081019/'),
  ('carnosine', 'Carnosine and advanced glycation end products: a systematic review', '5/5 · Interactions · Amino Acids, 2018', 'https://pubmed.ncbi.nlm.nih.gov/29858687/'),
  ('glutathione', 'Randomized controlled trial of oral glutathione supplementation on body stores of glutathione', '1/5 · Efficacy · Eur J Nutr, 2015', 'https://pubmed.ncbi.nlm.nih.gov/24791752/'),
  ('glutathione', 'Heavy metals: toxicity and human health effects', '2/5 · Mechanism · Arch Toxicol, 2025', 'https://pubmed.ncbi.nlm.nih.gov/39567405/'),
  ('glutathione', 'Exploring the Safety and Efficacy of Glutathione Supplementation for Skin Lightening: A Narrative Review', '3/5 · Safety · Cureus, 2025', 'https://pubmed.ncbi.nlm.nih.gov/40013212/'),
  ('glutathione', 'A Targeted Metabolomic Assessment of Oral Glutathione Bioavailability and Safety in Humans: A Randomized Crossover Clinical Trial', '4/5 · Practical · Antioxidants (Basel), 2026', 'https://pubmed.ncbi.nlm.nih.gov/41897500/'),
  ('glutathione', 'The Multifaceted Therapeutic Role of N-Acetylcysteine (NAC) in Disorders Characterized by Oxidative Stress', '5/5 · Interactions · Curr Neuropharmacol, 2021', 'https://pubmed.ncbi.nlm.nih.gov/33380301/'),
  ('na-selank-amidate', 'Functional Connectomic Approach to Studying Selank and Semax Effects', '1/5 · Efficacy · Dokl Biol Sci, 2020', 'https://pubmed.ncbi.nlm.nih.gov/32342318/'),
  ('na-selank-amidate', 'Selank, Peptide Analogue of Tuftsin, Protects Against Ethanol-Induced Memory Impairment by Regulating of BDNF Content in the Hippocampus and Prefrontal Cortex in Rats', '2/5 · Mechanism · Bull Exp Biol Med, 2019', 'https://pubmed.ncbi.nlm.nih.gov/31625062/'),
  ('na-selank-amidate', 'Nose-to-brain drug delivery: An update on clinical challenges and progress towards approval of anti-Alzheimer drugs', '3/5 · Practical · J Control Release, 2018', 'https://pubmed.ncbi.nlm.nih.gov/29772289/'),
  ('na-selank-amidate', 'Influence of long-term treatment with tuftsin analogue TP-7 on the anxiety-phobic states and body weight', '4/5 · Interactions · Pharmacol Rep, 2006', 'https://pubmed.ncbi.nlm.nih.gov/16963804/'),
  ('na-selank-amidate', 'Linezolid-associated serotonin toxicity: a systematic review', '5/5 · Further reading · Eur J Clin Pharmacol, 2023', 'https://pubmed.ncbi.nlm.nih.gov/37129603/'),
  ('livagen', 'DNA of Neutrophil Extracellular Traps Binds TMCO6 to Impair CD8+ T-cell Immunity in Hepatocellular Carcinoma', '1/5 · Efficacy · Cancer Res, 2024', 'https://pubmed.ncbi.nlm.nih.gov/38381538/'),
  ('livagen', 'Editing DNA Methylation in the Mammalian Genome', '2/5 · Mechanism · Cell, 2016', 'https://pubmed.ncbi.nlm.nih.gov/27662091/'),
  ('livagen', 'Peptide Regulation of Cell Differentiation', '3/5 · Safety · Stem Cell Rev Rep, 2020', 'https://pubmed.ncbi.nlm.nih.gov/31808038/'),
  ('livagen', '[The influence of the peptide bioregulator prostamax on heterochromatin of human lymphocytes in situ]', '4/5 · Practical · Biofizika, 2004', 'https://pubmed.ncbi.nlm.nih.gov/15612551/'),
  ('livagen', 'Human trials exploring anti-aging medicines', '5/5 · Interactions · Cell Metab, 2024', 'https://pubmed.ncbi.nlm.nih.gov/38181790/'),
  ('follistatin-344', 'The impact of weight loss on fat-free mass, muscle, bone and hematopoiesis health: Implications for emerging pharmacotherapies aiming at fat reduction and lean mass preservation', '1/5 · Efficacy · Metabolism, 2024', 'https://pubmed.ncbi.nlm.nih.gov/39481534/'),
  ('follistatin-344', 'Activin receptor signaling', '2/5 · Mechanism · Growth Factors, 2004', 'https://pubmed.ncbi.nlm.nih.gov/15253386/'),
  ('follistatin-344', 'Safety and efficacy of apitegromab in nonambulatory type 2 or type 3 spinal muscular atrophy (SAPPHIRE): a phase 3, double-blind, randomised, placebo-controlled trial', '3/5 · Safety · Lancet Neurol, 2025', 'https://pubmed.ncbi.nlm.nih.gov/40818473/'),
  ('follistatin-344', 'Follistatin Gene Therapy Improves Ambulation in Becker Muscular Dystrophy', '4/5 · Practical · J Neuromuscul Dis, 2015', 'https://pubmed.ncbi.nlm.nih.gov/27858738/'),
  ('follistatin-344', 'Bimagrumab: an investigational human monoclonal antibody against activin type II receptors for treating obesity', '5/5 · Interactions · J Basic Clin Physiol Pharmacol, 2024', 'https://pubmed.ncbi.nlm.nih.gov/39385353/'),
  ('igf-1-lr3', 'Mechanisms of IGF-1-Mediated Regulation of Skeletal Muscle Hypertrophy and Atrophy', '1/5 · Efficacy · Cells, 2020', 'https://pubmed.ncbi.nlm.nih.gov/32858949/'),
  ('igf-1-lr3', 'Insulin-like growth factor binding protein-1: identification, purification, and regulation in fetal and adult life', '2/5 · Mechanism · Adv Exp Med Biol, 1993', 'https://pubmed.ncbi.nlm.nih.gov/7514335/'),
  ('igf-1-lr3', 'Insulin Therapy and Diabetic Pregnancy', '3/5 · Safety · Am J Ther, 2020', 'https://pubmed.ncbi.nlm.nih.gov/31688066/'),
  ('igf-1-lr3', 'Insulin and insulin-like growth factors (IGFs) stimulate production of IGF-binding proteins by ovarian granulosa cells', '4/5 · Practical · Endocrinology, 1992', 'https://pubmed.ncbi.nlm.nih.gov/1379161/'),
  ('igf-1-lr3', 'Low protein intake is associated with a major reduction in IGF-1, cancer, and overall mortality in the 65 and younger but not older population', '5/5 · Interactions · Cell Metab, 2014', 'https://pubmed.ncbi.nlm.nih.gov/24606898/'),
  ('thymalin', '[Geroprotective effect of thymalin and epithalamin]', '1/5 · Efficacy · Adv Gerontol, 2002', 'https://pubmed.ncbi.nlm.nih.gov/12577695/'),
  ('thymalin', 'Anti-cytokine biologics for asthma in adults', '2/5 · Safety · Lancet, 2025', 'https://pubmed.ncbi.nlm.nih.gov/41038208/'),
  ('thymalin', 'Peptides of pineal gland and thymus prolong human life', '3/5 · Practical · Neuro Endocrinol Lett, 2003', 'https://pubmed.ncbi.nlm.nih.gov/14523363/'),
  ('thymalin', 'Regulatory T cells: mechanisms of differentiation and function', '4/5 · Interactions · Annu Rev Immunol, 2012', 'https://pubmed.ncbi.nlm.nih.gov/22224781/'),
  ('thymalin', 'Experimental and clinical study of the thymus polypeptide factor thymalin', '5/5 · Further reading · Hum Physiol, 1984', 'https://pubmed.ncbi.nlm.nih.gov/6336212/'),
  ('thymogen', 'Natural killer cell cytolytic activity is necessary for in vivo antitumor activity of the dipeptide L-glutamyl-L-tryptophan', '1/5 · Efficacy · Int J Cancer, 2003', 'https://pubmed.ncbi.nlm.nih.gov/12845648/'),
  ('thymogen', 'Pidotimod: the state of art', '2/5 · Safety · Clin Mol Allergy, 2015', 'https://pubmed.ncbi.nlm.nih.gov/25999796/'),
  ('thymogen', 'Trained immunity induction by the inactivated mucosal vaccine MV130 protects against experimental viral respiratory infections', '3/5 · Practical · Cell Rep, 2022', 'https://pubmed.ncbi.nlm.nih.gov/34986349/'),
  ('thymogen', 'Cut to the chase: a review of CD26/dipeptidyl peptidase-4''s (DPP4) entanglement in the immune system', '4/5 · Interactions · Clin Exp Immunol, 2016', 'https://pubmed.ncbi.nlm.nih.gov/26919392/'),
  ('thymogen', '[Application thymogen for preoperative preparation of elderly patients with tumor processes in abdominal cavity]', '5/5 · Further reading · Adv Gerontol, 2011', 'https://pubmed.ncbi.nlm.nih.gov/21957588/')
) as t(slug, title, meta, url) on t.slug = g.slug
where not exists (
  select 1 from public.glossary_research r where r.glossary_id = g.id and r.url = t.url
);

update public.glossary set goal_tags = array_append(goal_tags, 'Energy')
where slug in ('mots-c', 'ss-31') and not ('Energy' = any(goal_tags));
