-- The serving size on every product's label.
--
-- PROMPT_V2.md section 1: replace "no specific recommendation" with a real
-- number for every product, sourced rather than invented. Tier (a) is the label
-- serving, and it is available for all 250 products in the catalogue --
-- including the botanicals that have no reference intake and never will,
-- because they are not nutrients and no authority publishes a figure for them.
--
-- This is the one number that is always true and always citable: it is what the
-- manufacturer filed with the NIH, not the app's opinion about what anyone
-- should take. legal.md draws exactly that line -- the app may reproduce a
-- third party's figure, it may never originate one.
--
-- GENERATED from scripts/ingredients.json, which is the DSLD API response for
-- each label. servings_per_day is the filing's own minDailyServings.
--
-- studied_low / studied_high (tier (c), the commonly-studied range for
-- non-nutrients) are declared here and left null. Populating them requires
-- tying each range to a specific paper already in that product's five
-- citations, which is a research task per ingredient rather than a fetch. A
-- range with no source is exactly the invented number legal.md warns about, so
-- the columns exist and stay empty until someone does that work.

alter table public.glossary
  add column if not exists serving_amount   numeric,
  add column if not exists serving_unit     text,
  add column if not exists serving_form     text,
  add column if not exists servings_per_day numeric default 1,
  add column if not exists studied_low      numeric,
  add column if not exists studied_high     numeric,
  add column if not exists studied_unit     text,
  add column if not exists studied_source_citation_id uuid
    references public.glossary_research(id) on delete set null;

comment on column public.glossary.serving_form is
  'The serving as the label prints it -- "2 Capsules", "1 Scoop". Shown as "Take ...".';
comment on column public.glossary.studied_low is
  'Low end of the commonly studied range. Null unless studied_source_citation_id points at a paper in this product''s own citations.';

-- A peptide has no serving and never will. See 0031.
alter table public.glossary
  drop constraint if exists glossary_peptides_have_no_serving;
alter table public.glossary
  add constraint glossary_peptides_have_no_serving
  check (kind <> 'peptide' or (serving_amount is null and studied_low is null and studied_high is null));

update public.glossary g
set serving_amount = v.serving_amount,
    serving_unit   = v.serving_unit,
    serving_form   = v.serving_form,
    servings_per_day = v.servings_per_day
from (values
  ('advanced-nutrition-by-zahler-methylfolate', 1, 'Capsule(s)', '1 Capsule', 1),
  ('allergy-research-group-lactobacillus', 1, 'Capsule(s)', '1 Capsule', 1),
  ('allergy-research-group-liquid-molybdenum', 0.05, 'mL', '0.05 mL', 1),
  ('aor-advanced-orthomolecular-research-advanced-active-green-tea', 1, 'Capsule(s)', '1 Capsule', 3),
  ('aor-advanced-orthomolecular-research-citicoline', 2, 'Capsule(s)', '2 Capsules', 1),
  ('aor-advanced-orthomolecular-research-premium-zinc-copper-balance', 1, 'Capsule(s)', '1 Capsule', 1),
  ('biochem-100-whey-isolate-protein-chocolate-peppermint', 26.2, 'Gram(s)', '26.2 Grams', 1),
  ('bluebonnet-niacin-100-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('bulksupplements-alpha-lipoic-acid', 600, 'mg', '600 mg', 1),
  ('bulksupplements-amla-extract', 1000, 'mg', '1000 mg', 1),
  ('bulksupplements-astragalus-extract', 1300, 'mg', '1300 mg', 1),
  ('bulksupplements-bee-propolis-powder', 1200, 'mg', '1200 mg', 1),
  ('bulksupplements-l-leucine', 2500, 'mg', '2500 mg', 1),
  ('bulksupplements-msm-methylsulfonylmethane-1500-mg', 2, 'Capsule(s)', '2 Capsules', 1),
  ('bulksupplements-mucuna-pruriens-extract', 500, 'mg', '500 mg', 1),
  ('bulksupplements-olive-leaf-extract', 750, 'mg', '750 mg', 1),
  ('bulksupplements-pantothenic-acid-vitamin-b5-powder-500-mg', 500, 'Milligram(s)', '500 Milligrams', 1),
  ('bulksupplements-phenylethylamine-hcl-pea', 150, 'mg', '150 mg', 1),
  ('bulksupplements-rice-protein', 30, 'Gram(s)', '30 Grams', 1),
  ('bulksupplements-saw-palmetto-extract-320-mg', 1, 'Softgel(s)', '1 Softgel', 1),
  ('bulksupplements-taurine', 500, 'mg', '500 mg', 1),
  ('bulksupplements-vitamin-b1-thiamine-mononitrate', 100, 'Milligram(s)', '100 Milligrams', 1),
  ('bulksupplements-vitamin-b12-1-methylcobalamin', 20, 'mg', '20 mg', 1),
  ('carlson-glucosamine-sulfate', 1, 'Capsule(s)', '1 Capsule', 2),
  ('codeage-berberine-phytosome', 1, 'Capsule(s)', '1 Capsule', 1),
  ('codeage-liposomal-urolithin-a', 2, 'Capsule(s)', '2 Capsules', 1),
  ('deva-vegan-omega-3-dha-epa', 1, 'Capsule(s)', '1 Capsule', 1),
  ('doctors-best-astaxanthin', 2, 'Veggie Softgel(s)', '2 Veggie Softgels', 1),
  ('doctors-best-bacopa-320-mg-with-synapsa', 1, 'Veggie Capsule(s)', '1 Veggie Capsule', 1),
  ('doctors-best-barley-beta-glucan', 1, 'Veggie Capsule(s)', '1 Veggie Capsule', 1),
  ('doctors-best-extra-strength-ginkgo-120-mg', 1, 'Veggie Capsule(s)', '1 Veggie Capsule', 1),
  ('doctors-best-fisetin-with-novusetin', 1, 'Veggie Capsule(s)', '1 Veggie Capsule', 1),
  ('doctors-best-fully-active-b-complex', 1, 'Veggie Capsule(s)', '1 Veggie Capsule', 1),
  ('doctors-best-fully-active-b12-1500-mcg', 1, 'Veggie Capsule(s)', '1 Veggie Capsule', 1),
  ('doctors-best-high-absorption-coq10-100-mg', 1, 'Veggie Capsule(s)', '1 Veggie Capsule', 1),
  ('doctors-best-l-citrulline-powder', 3, 'Gram(s)', '3 Grams', 1),
  ('doctors-best-l-tryptophan-500-mg', 1, 'Veggie Capsule(s)', '1 Veggie Capsule', 1),
  ('doctors-best-l-tyrosine-500-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('doctors-best-lithium-aspartate', 1, 'Capsule(s)', '1 Capsule', 1),
  ('doctors-best-nmn-12000-400-mg', 2, 'Veggie Capsule(s)', '2 Veggie Capsules', 1),
  ('doctors-best-phosphatidyl-serine-with-serinaid-100-mg', 1, 'Softgel(s)', '1 Softgel', 3),
  ('doctors-best-pure-l-arginine-powder', 6, 'Gram(s)', '6 Grams', 1),
  ('doctors-best-stabilized-r-lipoic-acid-100-mg', 1, 'Veggie Capsule(s)', '1 Veggie Capsule', 1),
  ('doctors-best-vegan-omega-3-2000-mg', 2, 'Veggie Softgel(s)', '2 Veggie Softgels', 1),
  ('douglas-laboratories-vitamin-k2-menaquinone-7', 1, 'Vegetarian Capsule(s)', '1 Vegetarian Capsule', 1),
  ('energyfirst-chromium-picolinate', 1, 'Capsule(s)', '1 Capsule', 1),
  ('finest-nutrition-biotin-5-000-mcg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('gematria-vitamin-c-complex', 3, 'Capsule(s)', '3 Capsules', 2),
  ('gnc-beyond-raw-chemistry-labs-betaine-anhydrous-2-5-grams', 2.53, 'Gram(s)', '2.53 Grams', 1),
  ('gnc-beyond-raw-digestive-enzymes', 1, 'Capsule(s)', '1 Capsule', 1),
  ('havasu-nutrition-ginkgo-biloba-phosphatidylserine', 1, 'Capsule(s)', '1 Capsule', 1),
  ('health-thru-nutrition-naturally-lutein-with-zeaxanthin-20-mg', 1, 'Softgel(s)', '1 Softgel', 1),
  ('healths-harmony-california-spirulina', 1, 'Vegetable Capsule(s)', '1 Vegetable Capsule', 1),
  ('herbadiet-panax-ginseng-extract', 300, 'mg', '300 mg', 1),
  ('herbadiet-trans-resveratrol', 1, 'Capsule(s)', '1 Capsule', 2),
  ('hi-tech-pharmaceuticals-potassium-iodide-130-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('host-defense-brain-energy', 3, 'Gram(s)', '3 Grams', 1),
  ('host-defense-chaga-extract', 1, 'mL', '1 mL', 2),
  ('host-defense-cordyceps', 2, 'Capsule(s)', '2 Capsules', 1),
  ('host-defense-lions-mane', 2, 'Capsule(s)', '2 Capsules', 1),
  ('host-defense-lions-mane-extract', 1, 'mL', '1 mL', 2),
  ('host-defense-maitake-extract', 1, 'mL', '1 mL', 2),
  ('host-defense-mycommunity', 2, 'Capsule(s)', '2 Capsules', 1),
  ('host-defense-reishi-extract', 1, 'mL', '1 mL', 2),
  ('host-defense-shiitake-extract', 1, 'mL', '1 mL', 2),
  ('host-defense-sleep', 2, 'Capsule(s)', '2 Capsules', 1),
  ('host-defense-stamets-7-extracts', 1, 'mL', '1 mL', 2),
  ('host-defense-turkey-tail', 2, 'Capsule(s)', '2 Capsules', 1),
  ('jarrow-formulas-5-htp-100-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('jarrow-formulas-alpha-gpc-300-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('jarrow-formulas-beta-glucan-250-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('jarrow-formulas-borage-seed-oil-1200-mg', 1, 'Softgel(s)', '1 Softgel', 1),
  ('jarrow-formulas-carotenall', 1, 'Softgel(s)', '1 Softgel', 1),
  ('jarrow-formulas-citicoline-cdp-choline-250-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('jarrow-formulas-colostrum-prime-life-400-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('jarrow-formulas-evening-primrose-1300-mg', 1, 'Softgel(s)', '1 Softgel', 1),
  ('jarrow-formulas-hyaluronic-acid-120-mg', 2, 'Capsule(s)', '2 Capsules', 1),
  ('jarrow-formulas-jarro-dophilus-eps-25-billion', 1, 'Capsule(s)', '1 Capsule', 1),
  ('jarrow-formulas-l-carnitine-500-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('jarrow-formulas-lactoferrin-250-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('jarrow-formulas-mastic-gum-1000-mg', 2, 'Capsule(s)', '2 Capsules', 1),
  ('jarrow-formulas-opcs-95-100-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('jarrow-formulas-pqq-20-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('jarrow-formulas-prebiotic-inulin-fos', 3.8, 'Gram(s)', '3.8 Grams', 1),
  ('jarrow-formulas-ps100-100-mg', 1, 'Softgel(s)', '1 Softgel', 1),
  ('jarrow-formulas-qh-absorb-200-mg', 1, 'Softgel(s)', '1 Softgel', 1),
  ('jarrow-formulas-saccharomyces-boulardii-mos', 1, 'Capsule(s)', '1 Capsule', 1),
  ('jarrow-formulas-theanine-200-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('klean-athlete-klean-b-complex', 1, 'Vegetarian Capsule(s)', '1 Vegetarian Capsule', 1),
  ('klean-athlete-klean-bcaa-peak-atp', 8.6, 'Gram(s)', '8.6 Grams', 1),
  ('klean-athlete-klean-casein-vanilla-custard', 30.7, 'Gram(s)', '30.7 Grams', 1),
  ('klean-athlete-klean-creatine', 5, 'Gram(s)', '5 Grams', 1),
  ('klean-athlete-klean-electrolytes', 1, 'Vegetarian Capsule(s)', '1 Vegetarian Capsule', 1),
  ('klean-athlete-klean-endurance', 1, 'Chewable Tablet(s)', '1 Chewable Tablet', 1),
  ('klean-athlete-klean-essential-aminos-hmb', 9.15, 'Gram(s)', '9.15 Grams', 1),
  ('klean-athlete-klean-focus', 3, 'Vegetarian Capsule(s)', '3 Vegetarian Capsules', 1),
  ('klean-athlete-klean-glutamine', 5.46, 'Gram(s)', '5.46 Grams', 1),
  ('klean-athlete-klean-isolate-chocolate', 29, 'Gram(s)', '29 Grams', 1),
  ('klean-athlete-klean-magnesium', 1, 'Vegetarian Capsule(s)', '1 Vegetarian Capsule', 1),
  ('klean-athlete-klean-melatonin', 0.86, 'mL', '0.86 mL', 1),
  ('klean-athlete-klean-multivitamin', 2, 'Tablet(s)', '2 Tablets', 1),
  ('klean-athlete-klean-omega', 1, 'Softgel(s)', '1 Softgel', 1),
  ('klean-athlete-klean-plant-based-protein-vanilla', 36, 'Gram(s)', '36 Grams', 1),
  ('klean-athlete-klean-sr-beta-alanine', 2, 'Tablet(s)', '2 Tablets', 2),
  ('klean-athlete-klean-zinc', 1, 'Chewable Tablet(s)', '1 Chewable Tablet', 1),
  ('krk-supplements-choline-bitartrate', 2, 'Capsule(s)', '2 Capsules', 2),
  ('life-extension-acetyl-l-carnitine-arginate', 1, 'Capsule(s)', '1 Capsule', 3),
  ('life-extension-advanced-olive-leaf-vascular-support', 1, 'Vegetarian Capsule(s)', '1 Vegetarian Capsule', 2),
  ('life-extension-bio-collagen-with-patented-uc-ii-40-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('life-extension-black-cumin-seed-oil-and-bio-curcumin', 1, 'Softgel(s)', '1 Softgel', 2),
  ('life-extension-calm-mag', 1, 'Vegetarian Capsule(s)', '1 Vegetarian Capsule', 1),
  ('life-extension-citicoline-cdp-choline', 1, 'Capsule(s)', '1 Capsule', 1),
  ('life-extension-cognitex-elite', 2, 'Tablet(s)', '2 Tablets', 1),
  ('life-extension-creatine-capsules', 2, 'Capsule(s)', '2 Capsules', 2),
  ('life-extension-d-ribose-powder', 5000, 'mg', '5000 mg', 1),
  ('life-extension-dopamine-advantage', 1, 'Vegetarian Capsule(s)', '1 Vegetarian Capsule', 1),
  ('life-extension-echinacea-elite', 1, 'Vegetarian Capsule(s)', '1 Vegetarian Capsule', 2),
  ('life-extension-enhanced-sleep-without-melatonin', 1, 'Vegetarian Capsule(s)', '1 Vegetarian Capsule', 1),
  ('life-extension-fast-acting-liquid-melatonin', 1, 'mL', '1 mL', 1),
  ('life-extension-glycine-1000-mg', 1, 'Vegetarian Capsule(s)', '1 Vegetarian Capsule', 1),
  ('life-extension-huperzine-a-200-mcg', 1, 'Vegetarian Capsule(s)', '1 Vegetarian Capsule', 1),
  ('life-extension-l-arginine-caps-700-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('life-extension-l-tryptophan-500-mg', 1, 'Vegetarian Capsule(s)', '1 Vegetarian Capsule', 1),
  ('life-extension-lactoferrin-caps', 1, 'Capsule(s)', '1 Capsule', 1),
  ('life-extension-mega-epa-dha', 2, 'Softgel(s)', '2 Softgels', 1),
  ('life-extension-optimized-saffron', 1, 'Vegetarian Capsule(s)', '1 Vegetarian Capsule', 2),
  ('life-extension-palmettoguard', 1, 'Softgel(s)', '1 Softgel', 1),
  ('life-extension-senolytic-activator', 3, 'Capsule(s)', '3 Capsules', 1),
  ('life-extension-skin-restoring-ceramides', 1, 'Liquid Vegetarian Capsule(s)', '1 Liquid Vegetarian Capsule', 1),
  ('life-extension-tart-cherry-with-cherrypure', 1, 'Vegetarian Capsule(s)', '1 Vegetarian Capsule', 1),
  ('mytrition-l-arginine', 1, 'Capsule(s)', '1 Capsule', 1),
  ('nature-made-hair-skin-nails', 1, 'Softgel(s)', '1 Softgel', 1),
  ('nature-made-l-theanine-chewable-200-mg', 1, 'Tablet(s)', '1 Tablet', 1),
  ('nature-made-melatonin-200-mg-l-theanine', 1, 'Softgel(s)', '1 Softgel', 1),
  ('nature-made-super-b-complex', 1, 'Tablet(s)', '1 Tablet', 1),
  ('nature-made-vitamin-b-12-500-mcg', 1, 'Tablet(s)', '1 Tablet', 1),
  ('natures-craft-turmeric-curcumin', 1, 'Vegetarian Capsule(s)', '1 Vegetarian Capsule', 2),
  ('natures-way-riboflavin-vitamin-b2-100-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('new-sun-hyaluronic-acid', 2, 'Vegetarian Capsule(s)', '2 Vegetarian Capsules', 1),
  ('nhc-natural-healthy-concepts-n-acetyl-cysteine', 1, 'Capsule(s)', '1 Capsule', 1),
  ('nobi-nutrition-sambucus-elderberry', 1, 'Capsule(s)', '1 Capsule', 1),
  ('now-acerola-4-1-extract-powder', 3.2, 'Gram(s)', '3.2 Grams', 1),
  ('now-b-2-100-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('now-boron-3-mg', 1, 'Veg Capsule(s)', '1 Veg Capsule', 1),
  ('now-boswellia-extract-plus-turmeric-root', 1, 'Vegetarian Capsule(s)', '1 Vegetarian Capsule', 1),
  ('now-extra-strength-lecithin', 2, 'Softgel(s)', '2 Softgels', 1),
  ('now-gamma-e-tocopherols', 1, 'Softgel(s)', '1 Softgel', 1),
  ('now-l-tyrosine', 0.35, 'Gram(s)', '0.35 Grams', 1),
  ('now-maca-500-mg', 1, 'Veg Capsule(s)', '1 Veg Capsule', 1),
  ('now-magnesium-malate-caps', 1, 'Veg Capsule(s)', '1 Veg Capsule', 3),
  ('now-melatonin-5-mg', 1, 'Tablet(s)', '1 Tablet', 1),
  ('now-sports-beta-alanine-powder', 2, 'Gram(s)', '2 Grams', 3),
  ('now-tribulus-1000-mg', 1, 'Tablet(s)', '1 Tablet', 1),
  ('nutracraft-rhodiola-rosea', 2, 'Capsule(s)', '2 Capsules', 1),
  ('nutrakey-health-performance-l-citrulline-malate', 2, 'Gram(s)', '2 Grams', 2),
  ('nutricology-calcium-citrate', 1, 'Capsule(s)', '1 Capsule', 1),
  ('nutricology-magnesium-citrate', 1, 'Capsule(s)', '1 Capsule', 1),
  ('nutricology-potassium-citrate', 1, 'Capsule(s)', '1 Capsule', 1),
  ('ol-olympian-labs-ubiquinol', 1, 'Softgel(s)', '1 Softgel', 1),
  ('oregons-wild-harvest-ashwagandha', 1, 'Capsule(s)', '1 Capsule', 3),
  ('procaps-laboratories-chondroitin-sulfate-1200', 3, 'Capsule(s)', '3 Capsules', 1),
  ('procaps-laboratories-quercetin-500', 1, 'Capsule(s)', '1 Capsule', 1),
  ('protocol-for-life-balance-glycine', 0.25, 'tsp', '0.25 tsps', 1),
  ('protocol-for-life-balance-high-potency-d3-10-000-iu-cholecalciferol', 1, 'Veg Capsule(s)', '1 Veg Capsule', 1),
  ('pure-advantage-creatine-monohydrate', 3, 'Gram(s)', '3 Grams', 1),
  ('pure-encapsulations-alpha-lipoic-acid-600-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('pure-encapsulations-amino-nr', 3, 'Capsule(s)', '3 Capsules', 1),
  ('pure-encapsulations-ascorbyl-palmitate', 1, 'Capsule(s)', '1 Capsule', 1),
  ('pure-encapsulations-cats-claw', 1, 'Capsule(s)', '1 Capsule', 1),
  ('pure-encapsulations-glycine', 3, 'Capsule(s)', '3 Capsules', 1),
  ('pure-encapsulations-l-tryptophan', 2, 'Capsule(s)', '2 Capsules', 1),
  ('pure-encapsulations-lycopene-20-mg', 1, 'Softgel Capsule(s)', '1 Softgel Capsule', 1),
  ('pure-encapsulations-maca-3', 1, 'Capsule(s)', '1 Capsule', 1),
  ('pure-encapsulations-pantothenic-acid', 1, 'Capsule(s)', '1 Capsule', 1),
  ('pure-encapsulations-probiotic-50b', 1, 'Capsule(s)', '1 Capsule', 1),
  ('pure-encapsulations-selenium-selenomethionine', 1, 'Capsule(s)', '1 Capsule', 1),
  ('pure-myo-inositol', 4, 'Capsule(s)', '4 Capsules', 1),
  ('pure-prescriptions-zinc-picolinate', 1, 'Capsule(s)', '1 Capsule', 1),
  ('quality-of-life-labs-vitapqq-pyrroloquinoline-quinone', 1, 'Capsule(s)', '1 Capsule', 1),
  ('solgar-earth-source-fermented-koji-iron-27-mg', 1, 'Vegetable Capsule(s)', '1 Vegetable Capsule', 1),
  ('solgar-echinacea-herb-extract', 1, 'Vegetable Capsule(s)', '1 Vegetable Capsule', 1),
  ('solgar-flavo-zinc-lozenge', 1, 'Lozenge(s)', '1 Lozenge', 1),
  ('solgar-megasorb-coq-10-100-mg', 1, 'Softgel(s)', '1 Softgel', 1),
  ('solgar-sublingual-methylcobalamin-b12-5000-mcg', 1, 'nugget(s)', '1 nugget', 1),
  ('solgar-vegetal-silica', 1, 'Capsule(s)', '1 Capsule', 1),
  ('sports-research-astaxanthin-12-mg', 1, 'Softgel(s)', '1 Softgel', 1),
  ('sports-research-biotin-2500-mcg', 1, 'Veggie Softgel(s)', '1 Veggie Softgel', 1),
  ('sports-research-collagen-peptides-matcha', 12, 'Gram(s)', '12 Grams', 1),
  ('sports-research-evening-primrose-oil-500-mg', 3, 'Liquid Softgel(s)', '3 Liquid Softgels', 1),
  ('sports-research-hydrolyzed-collagen-peptides-vanilla', 11.65, 'Gram(s)', '11.65 Grams', 1),
  ('sports-research-magnesium-l-threonate-2000-mg', 3, 'Veggie Capsule(s)', '3 Veggie Capsules', 1),
  ('sports-research-marine-collagen-unflavored', 10, 'Gram(s)', '10 Grams', 1),
  ('sports-research-turmeric-curcumin-c3-complex', 1, 'Softgel(s)', '1 Softgel', 1),
  ('sports-research-whey-protein-isolate-dutch-chocolate', 40.5, 'Gram(s)', '40.5 Grams', 1),
  ('sundown-naturals-vitamin-a-10-000-iu', 1, 'Softgel(s)', '1 Softgel', 1),
  ('superiorlabs-l-lysine', 1, 'Capsule(s)', '1 Capsule', 1),
  ('superiorlabs-vitamin-b6', 1, 'Capsule(s)', '1 Capsule', 1),
  ('supersmart-bacopa-monnieri', 1, 'Capsule(s)', '1 Capsule', 1),
  ('supersmart-spermidine-3-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('swanson-5-htp-50-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('swanson-bamboo-extract', 1, 'Capsule(s)', '1 Capsule', 1),
  ('swanson-black-cumin-seed-oil-500-mg', 1, 'Liquid Veggie Capsule(s)', '1 Liquid Veggie Capsule', 1),
  ('swanson-boswellia-serrata-extract-125-mg', 1, 'Veggie Capsule(s)', '1 Veggie Capsule', 2),
  ('swanson-chinese-skullcap-400-mg', 1, 'Capsule(s)', '1 Capsule', 2),
  ('swanson-fisetin-100-mg', 1, 'Veggie Capsule(s)', '1 Veggie Capsule', 1),
  ('swanson-full-spectrum-fo-ti-500-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('swanson-full-spectrum-gotu-kola-435-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('swanson-full-spectrum-lavender-flower-400-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('swanson-huperzine-a-200-mcg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('swanson-inulin', 5, 'Gram(s)', '5 Grams', 1),
  ('swanson-l-methionine-500-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('swanson-lactobacillus-rhamnosus-with-fos', 1, 'Veggie EMBOCAP(s) AP', '1 Veggie EMBOCAP AP', 2),
  ('swanson-oregano-oil-liquid-extract', 0.17, 'mL', '0.17 mL', 3),
  ('swanson-rosemary-extract-500-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('swanson-sprouted-broccoli-seed-400-mg', 1, 'Veggie Capsule(s)', '1 Veggie Capsule', 1),
  ('teraputics-pure-life-magnesium-l-threonate', 4, 'Vegan Capsule(s)', '4 Vegan Capsules', 1),
  ('thorne-acetyl-l-carnitine-500-mg', 1, 'Capsule(s)', '1 Capsule', 2),
  ('thorne-amino-complex-lemon', 7.7, 'Gram(s)', '7.7 Grams', 1),
  ('thorne-basic-b-complex', 1, 'Capsule(s)', '1 Capsule', 1),
  ('thorne-beta-alanine-sr', 2, 'Tablet(s)', '2 Tablets', 1),
  ('thorne-biotin-8000-mcg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('thorne-boswellia-phytosome', 1, 'Capsule(s)', '1 Capsule', 2),
  ('thorne-broccoli-seed-extract', 1, 'Capsule(s)', '1 Capsule', 1),
  ('thorne-copper-bisglycinate', 1, 'Capsule(s)', '1 Capsule', 1),
  ('thorne-curcumin-phytosome-1000-mg', 1, 'Capsule(s)', '1 Capsule', 2),
  ('thorne-florasport-20b', 1, 'Capsule(s)', '1 Capsule', 1),
  ('thorne-gi-relief', 1, 'Capsule(s)', '1 Capsule', 1),
  ('thorne-glycine', 2, 'Capsule(s)', '2 Capsules', 1),
  ('thorne-iodine-and-tyrosine', 1, 'Capsule(s)', '1 Capsule', 2),
  ('thorne-iron-bisglycinate', 1, 'Capsule(s)', '1 Capsule', 1),
  ('thorne-joint-support-nutrients', 4, 'Capsule(s)', '4 Capsules', 1),
  ('thorne-l-arginine-plus', 3, 'Capsule(s)', '3 Capsules', 2),
  ('thorne-magnesium-bisglycinate', 3.11, 'Gram(s)', '3.11 Grams', 1),
  ('thorne-niacinamide', 1, 'Capsule(s)', '1 Capsule', 1),
  ('thorne-pantethine', 1, 'Capsule(s)', '1 Capsule', 2),
  ('thorne-pharmagaba-250', 1, 'Capsule(s)', '1 Capsule', 1),
  ('thorne-phosphatidylserine', 1, 'Capsule(s)', '1 Capsule', 2),
  ('thorne-riboflavin-5-phosphate', 1, 'Capsule(s)', '1 Capsule', 1),
  ('thorne-super-epa-425-mg', 1, 'Gelcap(s)', '1 Gelcap', 2),
  ('thorne-theanine', 1, 'Capsule(s)', '1 Capsule', 1),
  ('trace-minerals-research-ionic-manganese-10-mg', 1.25, 'mL', '1.25 mL', 1),
  ('village-vitality-sleep-with-valerian-and-melatonin', 1, 'Veggie Cap(s)', '1 Veggie Cap', 1),
  ('vincos-magnesium-glycinate', 0.5, 'Gram(s)', '0.5 Grams', 1),
  ('vital-proteins-collagen-peptides', 6, 'Capsule(s)', '6 Capsules', 2),
  ('vitamin-world-acidophilus-and-psyllium-husk', 4, 'Capsule(s)', '4 Capsules', 1),
  ('vitamin-world-natural-e-400-iu-d-alpha-tocopherol', 1, 'Softgel(s)', '1 Softgel', 1),
  ('wakunaga-of-america-kyolic-aged-garlic-extract', 0.25, 'tsp', '0.25 tsps', 2),
  ('wonder-laboratories-silymarin-milk-thistle', 1, 'Softgel(s)', '1 Softgel', 2),
  ('woodstock-vitamins-l-theanine-200-mg', 1, 'Capsule(s)', '1 Capsule', 1),
  ('zhou-saw-palmetto', 1, 'Capsule(s)', '1 Capsule', 1)
) as v(slug, serving_amount, serving_unit, serving_form, servings_per_day)
where g.slug = v.slug and g.kind = 'supplement';

do $$
declare
  with_serving integer;
  total        integer;
begin
  select count(*) filter (where serving_amount is not null), count(*)
    into with_serving, total
  from public.glossary where kind = 'supplement';
  raise notice 'servings: % of % supplements carry a label serving', with_serving, total;
end $$;
